//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Input/InputPlayer.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputPlayer : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputPlayer()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputPlayer"",
    ""maps"": [
        {
            ""name"": ""Barquinho"",
            ""id"": ""62f103cb-632b-4f44-a0b1-04ea52f05612"",
            ""actions"": [
                {
                    ""name"": ""Look"",
                    ""type"": ""Value"",
                    ""id"": ""a99d4e76-21a2-4657-8eb6-61f915d56fc6"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""c4602adc-3d48-4199-be26-75416c18da49"",
                    ""path"": ""<XInputController>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b879365a-6150-4efe-b5c8-15a2e6a60b52"",
                    ""path"": ""<DualShockGamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a5396092-f25a-445f-a1c9-f35a43bae435"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Barquinho
        m_Barquinho = asset.FindActionMap("Barquinho", throwIfNotFound: true);
        m_Barquinho_Look = m_Barquinho.FindAction("Look", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Barquinho
    private readonly InputActionMap m_Barquinho;
    private IBarquinhoActions m_BarquinhoActionsCallbackInterface;
    private readonly InputAction m_Barquinho_Look;
    public struct BarquinhoActions
    {
        private @InputPlayer m_Wrapper;
        public BarquinhoActions(@InputPlayer wrapper) { m_Wrapper = wrapper; }
        public InputAction @Look => m_Wrapper.m_Barquinho_Look;
        public InputActionMap Get() { return m_Wrapper.m_Barquinho; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(BarquinhoActions set) { return set.Get(); }
        public void SetCallbacks(IBarquinhoActions instance)
        {
            if (m_Wrapper.m_BarquinhoActionsCallbackInterface != null)
            {
                @Look.started -= m_Wrapper.m_BarquinhoActionsCallbackInterface.OnLook;
                @Look.performed -= m_Wrapper.m_BarquinhoActionsCallbackInterface.OnLook;
                @Look.canceled -= m_Wrapper.m_BarquinhoActionsCallbackInterface.OnLook;
            }
            m_Wrapper.m_BarquinhoActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Look.started += instance.OnLook;
                @Look.performed += instance.OnLook;
                @Look.canceled += instance.OnLook;
            }
        }
    }
    public BarquinhoActions @Barquinho => new BarquinhoActions(this);
    public interface IBarquinhoActions
    {
        void OnLook(InputAction.CallbackContext context);
    }
}
